services:
  - type: web
    name: tubedigest-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: your_postgresql_connection_string_here
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id_here
      - key: GOOGLE_CLIENT_SECRET
        value: your_google_client_secret_here
      - key: GOOGLE_REDIRECT_URI
        value: your_render_app_url/api/auth/google/callback
      - key: TOKEN_ENC_KEY
        value: your_strong_random_key_here
      - key: SMTP_HOST
        value: your_smtp_host_here
      - key: SMTP_PORT
        value: your_smtp_port_here
      - key: SMTP_USER
        value: your_smtp_username_here
      - key: SMTP_PASS
        value: your_smtp_password_here
      - key: SMTP_FROM
        value: your_smtp_from_email_here
      - key: APP_URL
        value: your_render_app_url_here
      - key: FRONTEND_URL
        value: your_frontend_url_here
